#cloud-config
timezone: Asia/Riyadh
#Disable firewalld 
runcmd:
    - systemctl disable firewalld.service
    - systemctl stop firewalld.service
    - sed -i 's/enforcing/disabled/g' /etc/selinux/config /etc/selinux/config 
    - for i in $(seq 1 10); do
            device="/dev/disk/azure/scsi1/lun$((i-1))";
            mountpoint="u$(printf "%02d" $i)";
            if [ -b $device ]; then
              echo "Setting up $device as $mountpoint";
              vgcreate $mountpoint"vg" $device;
              lvcreate -l 100%VG -n $mountpoint"lv" $mountpoint"vg";
              mkfs.xfs /dev/"$mountpoint"vg/"$mountpoint"lv;
              mkdir -p /$mountpoint;
              echo "/dev/"$mountpoint"vg/"$mountpoint"lv       /"$mountpoint"                  xfs     defaults        0 2" >> /etc/fstab;
              mount /$mountpoint;
            else
              echo "$device not found, skipping";
            fi;
          done
#set search domain from dhcp 
write_files:
  - path: /etc/dhcp/dhclient.conf
    content: | 
       supersede domain-search "albtests.com"
    append: true
#Create Unix Admin User 
users:
  - default
  - name: unixadmin
    gecos: Unix Team Admin User
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users,wheel
    hashed_passwd: '$6$D5BM.uromWpiMoUW$ESEB6Zaph0p0xFtOvVPMOFLjM9losVnMbSqJeFTAuvrjU0EcC0JaJZtJFLK.1ghKaiLhtR.sURn.mtsaLl5zb/'
    lock_passwd: false
    shell: /bin/bash
#Reboot the system wait for 2 min 
power_state:
    delay: now
    mode: reboot
    message: Rebooting......
    timeout: 30
    condition: True